apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketing-landing-page
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.7.0
    chart: podinfo
    helm:
      parameters:
        - name: ui.message
          value: "¡Hola desde Marketing! 🚀 Oferta Especial"
        - name: replicaCount
          value: "2"
  destination:
    server: https://kubernetes.default.svc
    namespace: marketing-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
