apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-sync
  namespace: backend-ns
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager-backend
    kind: ClusterSecretStore
  target:
    name: my-db-creds # Este será el nombre final en Kubernetes
    creationPolicy: Owner
  data:
  - secretKey: db_password_k8s
    remoteRef:
      key: prod/db-password
      property: password
