apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # ✅ CORRECCIÓN: Usamos el repo oficial estable
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    # Dejamos que tome la última versión estable (HEAD)
    targetRevision: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
