apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # ✅ CAMBIO: Usamos Podinfo que es 100% fiable para demos
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: 6.7.0
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
