apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/observed-k8s/
    targetRevision: 0.1.0
    chart: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
